name: Django CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ["3.6", "3.7", "3.8"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Selenium Chrome Driver (OSX)
        if: runner.os == 'macOs'
        run: brew cask install chromedriver
      - name: Install Selenium Chrome Driver (Windows)
        if: runner.os == 'Windows'
        uses: crazy-max/ghaction-chocolatey@v1
        with:
          args: install googlechrome chromedriver2
      - name: Setup Python ${{ matrix.python }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          cp .env.example .env
          python manage.py test
